"""updating user table

Revision ID: 0789ccd4f067
Revises: b73f22ea65bc
Create Date: 2025-05-17 18:29:28.942829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0789ccd4f067'
down_revision: Union[str, None] = 'b73f22ea65bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('user_password', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('Users', sa.Column('updated_on', sa.DateTime(), nullable=False))
    op.drop_column('Users', 'createdOn')
    op.drop_column('Users', 'updatedOn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updatedOn', sa.DATETIME(), nullable=False))
    op.add_column('Users', sa.Column('createdOn', sa.DATETIME(), nullable=False))
    op.drop_column('Users', 'updated_on')
    op.drop_column('Users', 'created_on')
    op.drop_column('Users', 'user_password')
    # ### end Alembic commands ###
