"""creating user table

Revision ID: b73f22ea65bc
Revises: 
Create Date: 2025-05-17 12:46:56.864822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73f22ea65bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_Users_uid'), 'Users', ['uid'], unique=True)
    op.create_index(op.f('ix_Users_user_email'), 'Users', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_user_email'), table_name='Users')
    op.drop_index(op.f('ix_Users_uid'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
